---
- hosts: all
  name: apply common configuration to all of the hosts
  sudo: true

  roles:
  - common

- hosts: mta
  name: apply configuration to the MTA 
  sudo: true

  vars_files:
  - vault.yml

  roles:
  - mta

- hosts: web
  name: apply configuration to the web front-end
  sudo: true

  roles:
  - squirrelmail
