---
# tasks file for mta

###FIX ME: Add the groups sasl and ssl-cert to the target MTA host.
###FIX ME: Then, create the postfix user and add to the sasl and ssl-cert group.  
###FIX ME: Create the dovecot user and add to the ssl-cert group


###FIX ME: Install the following pacakges:
   # - postfix
   # - dovecot-imapd
   # - sasl2-bin
   # - libsasl2-2
   # - libsasl2-modules
   # - openssl
   # - procmail

###FIX ME: open ports in the firewall for imap and smtpd (SSL also)

###FIX ME: Create self-signed certificate using the following command, and set the appropriate variables in the defaults/main.yml directory:
### openssl req -new -nodes -x509 -subj "{{ mail_self_signed_cert_subj }}" -days 3650 -keyout {{ mail_ssl_certificate_key }} -out {{ mail_ssl_certificate }} -extensions v3_ca
    
###FIX ME: Template and/or copy over the following configuration files:
# - /etc/mailname
# - /etc/postfix/main.cf
# - /etc/postfix/master.cf
# - /etc/postfix/sasl/smtpd.conf
# - /etc/default/saslauthd
# - /etc/aliases
# - /etc/dovecot/dovecot.conf
#  Then also run the command "newaliases" and notify a handler to restart the respective services

###FIX ME: Using the provided vault file, create the required hassh for the user passwords and then 
# create a task that will create the users remotely, iterating over each user and their 
# respective password, creating their home directories, updating their passwords each time it is run, and 
# setting their shell to /bin/bash

###FIX ME: Create first the mail directory in each user's home directory, then touch their inbox file so each
# user has ~/mail/inbox placed and chown to each respective user.

###FIX ME: Place the file /etc/fail2ban/filter.d/dovecot-pop3imap.conf from the template provided and notify a restart of fail2ban
