- name: install epel-release
  yum: name=epel-release state=present
  
- name: install commons packages (Red Hat)
  yum: name={{ item }} state=present
  with_items: packages

- name: stop iptables
  service: name=iptables state=stopped