---
- hosts: web:haproxy
  name: Sets up common role on all servers
  become: yes

  roles:
  - common

- hosts: web
  name: Configures apache on all the app servers
  become: yes

  roles:
  - apache

- hosts: haproxy
  name: Configures haproxy on the haproxy server
  become: yes

  roles:
  - haproxy 
